### ISSUE TITLE
About host files

### ISSUE THREAD

**Issue by x09326** [edwardtufte/tufte-css#106]
Hi, I'm going to host this lib on [cdnjs](https://cdnjs.com).

But I don't know which files should be added.
Would you help me to figure this?
Thanks.
https://github.com/cdnjs/cdnjs/issues/9181

**Comment by daveliepmann** [comment]
Per the README, you'll need `tufte.css` and the `et-book` font directory. 

@adamschwartz do you see any objections to hosting ETBook on a CDN?

**Comment by adamschwartz** [comment]
Already is (e.g. https://cdn.rawgit.com/edwardtufte/tufte-css/gh-pages/et-book/et-book-roman-line-figures/et-book-roman-line-figures.svg) so nope :)

**Comment by jez** [comment]
Oh, I already thought ET Book was on a CDN:
- http://www.jsdelivr.com/projects/font-et-book

Namely:

``` html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/font-et-book/0.1/et-book.min.css">
```

Which is what I just used in [Tufte Pandoc Jekyll](https://github.com/jez/tufte-pandoc-jekyll). I'm not sure how up-to-date it is.

**Comment by x09326** [comment]
Okay, thanks for you guys. :+1: 
I will send a pull request to cdnjs for hosting this lib recently.
