### ISSUE TITLE
Move notes below paragraphs on small screens

### ISSUE THREAD

**Issue by daveliepmann** [edwardtufte/tufte-css#11]
On small screens, sidenotes and margin notes should display underneath the paragraph they come from, not to the side, not disappeared altogether.

**Comment by ThomasA** [comment]
On my phone, "side-stuff" disappears completely (Firefox 39.0 on Android).
Great initiative by the way.

**Comment by thiagowfx** [comment]
I can confirm what @ThomasA said.

**Comment by ryan-mars** [comment]
+1 on having side notes display below paragraphs

**Comment by ghost** [comment]
I'm trying to do this but there is a problem, seems like this two behaviours can't be together (with pure CSS, as far as I know):
- Display the notes **underneath** the paragraph on small screens.
- Display the notes **exactly aside** the note number in big screens.

### Scenario 1

✓ Display notes underneath the paragraph in small screens.
✗ Display the notes exactly aside the note number in big screens.

**Small screen:**

![small-screen](https://cloud.githubusercontent.com/assets/2559808/9125383/7e00af42-3c5d-11e5-9c7e-abc41366bb80.png)

**Big screen:**

![big-screen](https://cloud.githubusercontent.com/assets/2559808/9125385/832cb826-3c5d-11e5-9987-b2b75076e7f1.png)

### Scenario 2

✗ Display notes underneath the paragraph in small screens.
✓ Display the notes exactly aside the note number in big screens.

**Small screen:**

![scen2-small-screen](https://cloud.githubusercontent.com/assets/2559808/9125424/f23601f0-3c5d-11e5-8c62-b57f92fcb7c1.png)

**Big screen:**

![scen2-big-screen](https://cloud.githubusercontent.com/assets/2559808/9125423/ed4678d2-3c5d-11e5-878f-b3d504da556a.png)

---

This could be done with Javascript though.

**Comment by daveliepmann** [comment]
@jameskolce You have precisely described my concern. I would like to avoid JavaScript and other additional dependencies for the time being. I think more thought is needed into alternative pure-CSS approaches.

**Comment by ghost** [comment]
@daveliepmann Do you think that is possible with only CSS?

**Comment by daveliepmann** [comment]
@jameskolce It depends. We need to define our goals, do some research on technical possibilities, and propose some alternative designs. Remember, the web is not a book, and sidenotes on a webpage are not sidenotes in print. 

This is related to #26.

**Comment by ghost** [comment]
In order to achieve **exactly** this effect we need to know the position of the sidenote number, and as far as I know that is not possible with pure CSS. 
However, I think we could move the sidenote to the beginning of the paragraph in large screens, and move it to the end in small screens, that would be acceptable in my opinion.

---

**Large:**
![large](https://cloud.githubusercontent.com/assets/2559808/9126918/ae4528dc-3c70-11e5-804f-6996110b4865.png)

**Small:**
![small](https://cloud.githubusercontent.com/assets/2559808/9126921/b1c5ee06-3c70-11e5-9a0b-d3656f499ed5.png)

---

I have the code for this, let me know what do you think so I can make a PR.

**Comment by daveliepmann** [comment]
@jameskolce I'm afraid I can't agree. The example document isn't a great sample of the kinds of web pages I think we want to support. (Which is why I'd like to see more examples, and more varied ones.) Relevant to this case, it doesn't demonstrate the use of long paragraphs. To my mind, keeping the sidenote _immediately_ adjacent to the text referencing it is a critical design goal. I'm not sure how to square that with mobile screens, but putting sidenotes at the top and bottom of paragraphs is, I think, not going to cut it.

I'd like to see your code regardless. It doesn't seem to be on [your branch](https://github.com/jameskolce/tufte-css)?

**Comment by ghost** [comment]
It is now: https://github.com/jameskolce/tufte-css/commit/a215ba2665319526b86fa844eec156a48d679797

**Comment by daveliepmann** [comment]
@jameskolce Thanks. I'm getting some side effects in the demo doc, using Chrome developer tools to pretend to be a small screen: 
- sidenotes floating to below the `newthought` small-caps, not the `p`
- the final period of a sidenote's sentence being pushed to the next paragraph

...and I'm still very wary of the confusion caused by, say, sidenotes 4 and 5 being beside the start of the paragraph rather than beside the citation they relate to. I just don't think it works.

**Comment by ghost** [comment]
Sorry I forgot to update the HTML. Here you go: https://github.com/jameskolce/tufte-css/commit/1e0c78cd60e1875a5293a2de812a5673d192efd8

Well, you proposed to have all the sidenotes at the bottom for small screens, for large paragraphs we couldn't even see the sidenote number, having everything at the beginning of the paragraph for large screens is not that bad in my opinion. Actually, I don't see a big problem with this which makes me think that it is matter of taste.

As you said, the web is not a book, and sidenotes on a webpage are not sidenotes in print. In this case we can't create the same sidenotes of a book in a website, but this is the closest solution we can get without using JS.

Just my opinion.

**Comment by ghost** [comment]
Your code here is similar to what I was thinking: https://github.com/jameskolce/tufte-css/blob/master/tufte.css#L126-L137

However, I was thinking that perhaps on screens less than a certain the following would apply:
- relatively position each `p`
- reposition each sidenote under `p` using `position:absolute;right:0;bottom:0;width:100%` and any other CSS needed to move the sidenote to full-left and give enough whitespace until the beginning of the next `p`

This is sort of the inverse of your current approach.

**Comment by ghost** [comment]
@xHN35RQ That is to put the sidenotes at the bottom of the paragraph in small screens while we maintain the original position in large screens, right?

**Comment by ghost** [comment]
I tried something like that and I get the desired result for large screens but on small ones:

![new](https://cloud.githubusercontent.com/assets/2559808/9128489/b246c27c-3c86-11e5-931f-6db013006d62.png)

The problem is that I can't give enough whitespace for the sidenote, I would need to provide a `margin-bottom` to each `p` that has a sidenote inside, but we don't have a selector in CSS for that (yet). And If I add a `margin-bottom` to the sidenote it just moves up since it is absolutely positioned.

**Comment by ghost** [comment]
Yes, that's looking closer to the goal. :+1: 

> If I add a margin-bottom to the sidenote it just moves up since it is absolutely positioned.

I rant into the same issue when I was trying to get it to work earlier... I think maybe either another selector is needed or maybe it would help to change all side-notes to `<aside>` as proposed in #24 since I think that would give more flexibility on styling, right?

**Comment by ghost** [comment]
That's pretty close, but there is no parent selector in CSS yet, something like `.sidenote-content < p` (select all `p` that are parents of `.sidenote-content` elements) would solve our problems, then we could add margin-bottom to those elements.

I don't think `<aside>` would help for this, since it is the same as a `div` or `section` just with a different semantic meaning. But let me know what ideas you have about it, maybe I'm forgetting about something.

**Comment by vincentbernat** [comment]
@jameskolce: about "yet", an "important" characteristic of CSS is that style of a later element cannot influence a current element (with a few bounded exceptions, like `:last-child`), mainly for performance reason: avoiding to reevaluate each rule several time on a change. Therefore, such a feature will "never" be implemented.

**Comment by ghost** [comment]
@vincentbernat Actually, in the draft of CSS selectors level 4 there is [:has()](https://drafts.csswg.org/selectors-4/#relational) which would work exactly like `<` in my _hypothetical_ example, `p:has(> .sidenote-content)` would solve our problem here, but it isn't implemented (as far as I know) and I don't know if it will be, maybe or maybe not.
But don't take it too seriously man, I was just saying, just to illustrate the situation.

**Comment by ghost** [comment]
> I don't think `<aside>` would help for this, since it is the same as a div or section just with a different semantic meaning. But let me know what ideas you have about it, maybe I'm forgetting about something

A `<span>` is an inline element while `<aside>` is not.

**Comment by kevinmarks** [comment]
another option would be to make the sidenotes click-to-expand on the narrow measure screens. The html element &lt;details>&lt;summary>1&lt;/summary> sidenote text goes here. &lt;/details> does this and can be styled appropriately.  (not implemented in firefox yet, so may need a polyfill)
<details><summary>

1</summary>

 sidenote text goes here. </details>

**Comment by daveliepmann** [comment]
To repeat @kevinmarks idea so the HTML can be seen:

`<details><summary>1</summary> sidenote text goes here. </details>` 

does this:

<details><summary>

1</summary>

 sidenote text goes here. </details>

**Comment by daveliepmann** [comment]
If `details/summary` were supported in FF and IE I would say that's the direction to go for small screens.

**Comment by crmackay** [comment]
I agree with the idea by @kevinmarks. i think the click to expand in place idea (in context) makes more sense than having it at the end of the paragraph. The intent of the sidenote is to allow the reader to quickly jump back and forth from the text to the margin content (sidenote, margin note, margin figure). 

This is lost if the margin content is at the end of the paragraph, especially on small screens where the end of the paragraph will likely be off screen. Instead the reader will have to scroll back and forth. If the content is quickly and unobtrusivley toggle-able, the reader could open, close, open, close at will.

You could do this with more pure css probably via a [checkbox toggle hack](http://tympanus.net/codrops/2012/02/21/accordion-with-css3/)

**Comment by kevinmarks** [comment]
do firefox and IE run on small screens much? FF mobile and win mobile are
hardly used compared to chrome/safari/android browser:
http://caniuse.com/#search=details

**Comment by ghost** [comment]
:+1: for the idea of toggling visibility on the side-notes.

**Comment by ghost** [comment]
The idea of @kevinmarks sounds good to me too.

**Comment by crmackay** [comment]
here is a demonstration:

this one splits the paragraph at the marker: https://jsbin.com/rahicu/edit?html,css,output

here is another (with minor animation) that splits the paragraph at the next line break: https://jsbin.com/huqeju/edit?css,output

**Comment by crmackay** [comment]
ok so I have demo'ed a few possibilities (images below):
1. collapsable(toggle-able) margin content that breaks the paragraph exactly where it's referenced
   - ![aug 08 2015 17 01](https://cloud.githubusercontent.com/assets/3801862/9152274/0a2a4134-3df0-11e5-9a26-5c03a0391163.gif)
2. collapsable(toggle-able) margin content that breaks the paragraph at the next line break
   - ![aug 08 2015 17 03](https://cloud.githubusercontent.com/assets/3801862/9152275/11823342-3df0-11e5-84f0-5845852abed9.gif)
3. always-visible margin content that breaks the paragraph exactly where it's referenced
   - ![image](https://cloud.githubusercontent.com/assets/3801862/9152217/7a2565a2-3ded-11e5-8776-adcad57df9ac.png)
4.  always-visible margin content that breaks the paragraph exactly at the next line break
   - ![image](https://cloud.githubusercontent.com/assets/3801862/9152224/9d39522e-3ded-11e5-83d6-267c8c26a9f3.png)

The collapsable option requires insertion of a fair bit more markup in the html (a label and input field just before the marginnote or sidenote). The static version is just a few changes to the css (`float:left` or `float:none`).

thoughts?

**Comment by vincentbernat** [comment]
I'll vote for the second solution. The text is interrupted at a natural point (like it was without the note) and don't get in the way of people not interested by the footnote (most people are not interested, otherwise, it shouldn't be a footnote).

**Comment by ghost** [comment]
Oh wow, option 2 looks very sexy. Well done! I like how it breaks at the next line break.

**Comment by daveliepmann** [comment]
Great work putting together these demos. The second option is definitely my favorite. After looking at the latest changes to small-screen sidenotes I am sure that they need to be toggle-able.

Is option 2 functional across browsers, including Firefox and mobile safari?

**Comment by crmackay** [comment]
Should be pretty universal since it uses some fairly standard css (famous last words), but I'll test it as thoroughly as I can before submitting a pull request.

The only potential problem is that it mucks up the html a bit. 

However, I imagine most people are not handwriting their `html`, but are instead using some sort of templating system or preprocessing from markdowm/asciidoc/reST/etc. So, this might not be an issue. 

For every sidenote or marginnote you need to put a `label` and `input` element just ahead of it like so:

``` html
<label for="sidenote-8" class="margin-toggle sidenote-number"></label>
<input type="checkbox" id="sidenote-8" class="margin-toggle"/>
<span class="sidenote">
  This is a sidenote
</span> 
```

``` html
<label for="marginote-2" class="margin-toggle">&#8853;</label>
<input type="checkbox" id="marginnote-2" class="margin-toggle"/>
<span class="marginnote">
  This is a marginnote
</span> 
```

**Comment by daveliepmann** [comment]
With the fix from @crmackay I'm considering this issue settled. I see toggling as the correct choice for small screens. Big thanks to everyone who weighed in and put in work on this!
