### ISSUE TITLE
article element has position relative

### ISSUE THREAD

**Issue by gheoan** [edwardtufte/tufte-css#113]
Is there a reason why the `article` element has [`position: relative`](https://github.com/edwardtufte/tufte-css/blob/1f77d86595a3bf66a367c0c8d3ed8e4a9fdd222a/tufte.css#L82)? It is like that since the [first commit](https://github.com/edwardtufte/tufte-css/commit/9f53cdfc48789fd2380d931fd4093f024d8813b1#diff-f18a581ae9dc15a8a2b31debc6480349R12). If it is not needed, it should be removed to reduce complexity of the CSS.

**Comment by daveliepmann** [comment]
Good catch. I cannot recall. I'd like to do some quick regression testing before taking it out but it definitely seems extraneous.

**Comment by rowild** [comment]
Isn't that necessary, so the sidenotes can be placed relatively?

**Comment by dracos** [comment]
The sidenotes are floated, not positioned. It's not clear why the sidenote/marginnote has position relative either (at least to me!).

**Comment by daveliepmann** [comment]
Thanks for the heads-up on this. Finally fixed it. Hopefully we're all correct and it wasn't holding up the foundation of someone's house.
