### ISSUE TITLE
content: counter defined twice

### ISSUE THREAD

**Issue by rowild** [edwardtufte/tufte-css#114]
At 
`[183] .sidenote-number:after, .sidenote:before { content: counter(sidenote-counter) " ";`
the "content: counter[...]" definition is not necessary, since either selector is defined separately just some lines below.

Also, maybe it is better not to use a space separator in the content:counter declaration, since it would insert an unwanted space between the annotation number and any potentially following interpunction (comma, dot).

**Comment by daveliepmann** [comment]
Fixed by #123, which is now merged, so closing. Thanks!
