### ISSUE TITLE
Firefox 56: brief FOUT, then invisible text for an unreasonably long time

### ISSUE THREAD

**Issue by shabbyrobe** [edwardtufte/tufte-css#119]
When browsing with Firefox 56 on macOS 10.12, I first see a usually brief, but sometimes not-so-brief flash of unstyled content. At worst this can last 2 seconds:

<img width="1360" alt="first" src="https://user-images.githubusercontent.com/288426/32428792-c5f4a910-c31b-11e7-9732-60fcb7dd4c76.png">

Next, all the text disappears and stays invisible for a substantial length of time. Never less than 2 seconds:

<img width="1357" alt="second" src="https://user-images.githubusercontent.com/288426/32428804-d0ddf9d0-c31b-11e7-8489-584affc122ce.png">

Until finally the page loads and appears as it seems it should:

<img width="1359" alt="third" src="https://user-images.githubusercontent.com/288426/32428805-d24a019c-c31b-11e7-8979-4b632ff4225e.png">

My internet speed is pretty standard for Australia, which is to say it is essentially awful.

**Comment by daveliepmann** [comment]
Could you re-test (with a cleared cache) now that 121 was merged?

**Comment by sondr3** [comment]
The FOUC is, and will be there, until you do something about how fonts are fetched and CSS is rendered in Firefox. I fixed the same problem for Gitea: https://github.com/go-gitea/gitea/pull/1728.

**Comment by ryuran** [comment]
`font-display: optional` for future ?
You can add woff2 font.

**Comment by daveliepmann** [comment]
Thanks for reporting this, and for the proposed solutions.

We won't be using a JS solution, as this is a CSS-only project. 

`font-display: optional` seems promising but it does not yet seem to have broad enough browser support. 

I am closing this until we see a well-supported CSS-only solution.
