### ISSUE TITLE
ET Bembo font licensing

### ISSUE THREAD

**Issue by vincentbernat** [edwardtufte/tufte-css#12]
Hi!

As far as I understand, ET Bembo is not licensed for free distribution. If it is, I doubt it will be licensed under the MIT license. Could you add a paragraph about that? The font has also been added to Edward Tufte's own project without any word about this. For example, in https://github.com/edwardtufte/presenter/commit/2be716427f52c34f4d89684b5409890cb5c54235.

**Comment by hastebrot** [comment]
The `package.json` [0] says it's under MIT. The font's source files (if `.suit` files are actually font sources?) are included along with generated `.eot`, `.ttf`, `.woff`, and `.svg` files [1].
- [0]: https://github.com/edwardtufte/presenter/blob/master/package.json
- [1]: https://github.com/edwardtufte/presenter/tree/master/font/et-bembo

**Comment by hastebrot** [comment]
Oh, `.suit` and `.dfont` are actually older Macintosh font formats, i.e. no font source files.

**Comment by vincentbernat** [comment]
The `package.json` file was not added by Tufte. I think this is likely that the licensing didn't get really discussed. But I may just be plain wrong.

**Comment by ghost** [comment]
See https://github.com/edwardtufte/presenter/issues/1
And https://www.edwardtufte.com/bboard/q-and-a-fetch-msg?msg_id=0000bm

**Comment by ghost** [comment]
This might be a possible replacement if ET Bembo is not available: https://www.google.com/fonts/specimen/Cardo

**Comment by hastebrot** [comment]
Cardo is also available here: https://github.com/google/fonts/tree/master/ofl/cardo

**Comment by ghost** [comment]
[Edward Tufte himself said](https://www.edwardtufte.com/bboard/q-and-a-fetch-msg?msg_id=0000bm#responses)

> "It is a typeface just to get my books from lead to computer; I'm not in the type distribution business so it will not be made available."

I'd assume this statement still holds true unless he's more recently stated otherwise.

**Comment by sathomas** [comment]
If you want a pull request that switches to Cardo (I do think it's a good substitute for Bembo), let me know and I'll put one together.

**Comment by ghost** [comment]
@sathomas that sounds great, thanks! Better safe than sorry! And perhaps a Gill Sans alternative too? Maybe Lato: https://www.google.com/fonts/specimen/Lato

BTW this is another alternative besides Cardo: https://www.google.com/fonts/specimen/EB+Garamond

Not sure which is more authentic to ET Bembo.

**Comment by daveliepmann** [comment]
I was under the mistaken impression that ETBembo was released under the MIT license as part of the `presenter` project. It was not. I am in contact with @adamschwartz to resolve the situation. 

My apologies for causing this confusion.

**Comment by ghost** [comment]
> My apologies for causing this confusion.

No problem, it should be straightforward to switch out for a different font. Thanks for making this fantastic CSS package. It came right when I needed something like it.

**Comment by sathomas** [comment]
Pull request https://github.com/daveliepmann/tufte-css/pull/15 available

**Comment by vyp** [comment]
@vincentbernat @hastebrot https://github.com/daveliepmann/tufte-css/pull/15#issuecomment-141708102 :smiley:

**Comment by vincentbernat** [comment]
:panda_face:

**Comment by adamschwartz** [comment]
https://github.com/edwardtufte/et-bembo :) more to come

**Comment by daveliepmann** [comment]
[ET Bembo is now free and open source](https://github.com/edwardtufte/et-bembo). Woo!
