### ISSUE TITLE
Underlining behavior for parentheses in <a> tags 

### ISSUE THREAD

**Issue by renandincer** [edwardtufte/tufte-css#127]
When using parentheses in <a> tags, the underline behaves like this:
![image](https://user-images.githubusercontent.com/1429100/33145529-8f7a1bd4-cf75-11e7-92e9-c1b559e3d14b.png)
while I'd expect it to look like this:
![image](https://user-images.githubusercontent.com/1429100/33145531-91c3dfc4-cf75-11e7-8883-ff0731d54eb4.png)

cc @adamschwartz

**Comment by adamschwartz** [comment]
Thanks! Now that [`text-decoration-skip-ink: auto`](https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/47BHtmz0jVY/itAC_xpwBgAJ) is a thing in Chrome Canary, it might be time to start only using the [SmartUnderline](https://github.com/cloudflare-apps/smart-underline) approach as a fallback for browsers which don’t support it.

**Comment by daveliepmann** [comment]
@renandincer At the moment, Tufte CSS clears descenders like this with a rather tricky workaround (see https://github.com/edwardtufte/tufte-css/blob/gh-pages/tufte.css#L151). You're right, it definitely has some imperfections. However improving its behavior is not simple, and I don't plan to allocate time to this feature in the near future. The fact that browsers seem to be slowly addressing this themselves makes change here even less likely.

@adamschwartz Browser support for those seems fairly sparse for the moment, but I agree that it would be nice to rely by default on baked-in browser support for clearing descenders, and only fall back to your (ingenious) `linear-gradient` workaround when necessary.

**Comment by adamschwartz** [comment]
@daveliepmann I think we’re on the same page. My suggestion is to use CSS `@supports` to check for the availability of `text-decoration-skip` (e.g.) and make the appropriate changes to enable that when it’s supported (and to not make any additional improvements to the `linear-gradient` version). 

So nice that feature testing can be done natively in CSS now.
