### ISSUE TITLE
Documentation erroneously claims "support" for Image Quilts, though the images were pre-made

### ISSUE THREAD

**Issue by spacehobo** [edwardtufte/tufte-css#128]
The documentation leads the reader to believe that one can specify a list of images to be quilted together thanks to the Tufte CSS.  In fact, the examples in the documentation are pre-crafted images that have simply been rendered using the other documented styles.

Either a feature should be written to arrange images in Tufte-style quilts, or the documentation should be amended for clarity.

**Comment by spacehobo** [comment]
Wow, you won't even update the docs to be less confusing?  That seems to go against the very philosophy of clarity that Tufte always espouses.

**Comment by ryan-mars** [comment]
@spacehobo Have you tried submitting a PR

**Comment by spacehobo** [comment]
Why should I?  `wontfix` means *won't*
