### ISSUE TITLE
css-grid?

### ISSUE THREAD

**Issue by fustkilas** [edwardtufte/tufte-css#130]
has anyone rewritten tufte-css in css-grid?

**Comment by daveliepmann** [comment]
Not to my knowledge. Feel free to ask around. I don't expect any rewrites in the foreseeable future.

**Comment by yb66** [comment]
@fustkilas Why not fork and start the rewrite? Perhaps you'll attract others to do that same or help you and then you can merge and merge until it's good enough.

iain

**Comment by jez** [comment]
Out of curiosity, what’s the benefit of rewriting using grid? It’s probably
only worth the rewrite if it enables the markup to be simpler, but the
markup is already pretty simple I think.

**Comment by fustkilas** [comment]
@daveliepmann @yb66 i have forked to https://github.com/fustkilas/tufte-css-grid and updated the readme with a roadmap. i will shortly begin with the first step.

@jez multiple benefits; off the top of my head i can think of: semantic markup, no divitis, grid extraordinarily simplifies responsive layouts, also i feel it fits with tufte's ethos more that any percentage/float solution ever can. 

i feel as i progress along more advantages (or drawbacks) will reveal themselves and i will try maintain a changelog, or some sort of doc comparing tufte-css with tufte-css-grid.

tufte's praxis with print is a highly optmized custom layout engine; after all, he started a printing press to print his books himself. tufte's books also reveal an intense use of gridding, and grids feature prominently in his work. not that i'm saying the web should imitate print; it shouldn't. i feel a minimum viable port will be simple to implement. let's see.

everyone is welcome to contribute.

**Comment by daveliepmann** [comment]
>@jez multiple benefits; off the top of my head i can think of: semantic markup, no divitis, grid extraordinarily simplifies responsive layouts, also i feel it fits with tufte's ethos more that any percentage/float solution ever can.

>tufte's praxis with print is a highly optmized custom layout engine; after all, he started a printing press to print his books himself. 

These two points encapsulate why I'm interested to see where tufte-css-grid goes, and why I encourage it as a separate endeavor. Tufte CSS is very intentionally a plain-CSS-only project with zero tooling, for reasons both aesthetic and practical. I fully acknowledge that this limits Tufte CSS: our descender-clearing solution is technically inferior to solutions that use JS; manual markup of sidenotes is more verbose and labor-intensive in plain HTML than it is with tools that convert from Markdown; we miss out on the benefits of CSS preprocessor toolchains and so on. That's OK. Different projects make different tradeoffs. I'm happy that folks have built on top of Tufte CSS to provide solutions in that space: [tufte-pandoc-css](https://github.com/edwardtufte/tufte-css/issues/21#issuecomment-258652736), [xmark](https://github.com/vieiro/xmark), [tufte-markdown](https://github.com/duzyn/tufte-markdown), and so on.
