### ISSUE TITLE
Sidenotes in Print

### ISSUE THREAD

**Issue by hillmancobs** [edwardtufte/tufte-css#131]
I noticed on the Tufte CSS page that if you print the page the sidenotes collapse and will not show up on the print-out. It there anyway to have them stay at the side or to be expanded if a page using Tufte CSS is printed?

**Comment by crmackay** [comment]
You should be able to do this by adding a `@media print{...} ` statement.

**Comment by wizardishungry** [comment]
I've noticed the opposite behavior - the font size and margins + sidebar make the text look enormous in print

**Comment by daveliepmann** [comment]
My apologies for the delayed response to this on my part. 

Tufte CSS has not supported printing since 81c72af. I consider the styling of printed documents to be out of scope for this project. Therefore I'm going to close this.

**Comment by keysmashes** [comment]
I don't suppose you could be persuaded that print is worth supporting? It seems a shame that sidenotes are totally inaccessible when printed.

Adding minimal support for print media would be pretty trivial – enclosing the entire media query for small screens in `@media not print {...}` basically works (the third epigraph on the example page overflows into the right-hand column, but that's about the only obvious issue).

**Comment by daveliepmann** [comment]
@anowlcalledjosh Restricting the scope of the project to exclude print was a considered decision. It rests on several factors, the greatest of which are probably these three:

 - handling print properly is a big task
 - this project is not under ongoing development
 - handling print in another CSS file or library is straightforward

I don't want to expand Tufte CSS's surface area for errors, I don't want to do the job poorly (such as your "trivial" approach that you admit is broken), and anyone who wants to tackle the problem has the ability to do so. Someone who actually does face the problem of "Tufte CSS for print" would be in a much better position to build a good solution, and to release that work open-source.
