### ISSUE TITLE
responsive horizontal rules

### ISSUE THREAD

**Issue by jboynyc** [edwardtufte/tufte-css#133]
I submitted a pull request, #132, that makes `hr` elements responsive. They currently aren't since https://github.com/edwardtufte/tufte-css/commit/1f77d86595a3bf66a367c0c8d3ed8e4a9fdd222a set their width to 55%.

**Comment by daveliepmann** [comment]
Nice catch.

**Comment by daveliepmann** [comment]
Closing this because I merged your fix in 132. Thank you.
