### ISSUE TITLE
baseline of sidenote/marginnote is not aligned with baseline of text

### ISSUE THREAD

**Issue by uhoreg** [edwardtufte/tufte-css#134]
Sidenotes/marginnotes seem to float above the baseline of the main text (baseline marked in blue):
![image](https://user-images.githubusercontent.com/1012976/43612303-e9f68734-9679-11e8-9fa4-0859ca6326f7.png)
Setting the margin-top of the sidenotes/marginnotes from 0 to 0.3rem seems to fix the issue:
![image](https://user-images.githubusercontent.com/1012976/43612375-270d855a-967a-11e8-911c-d78c2f4641c9.png)

**Comment by jez** [comment]
It’s a larger problem than this. Since the text is smaller, the entire grid is off. A principled way to solve it might be to make the body copy large enough so that the ratio of body to sidenote line height is 2:1.

Even if we just push the top line down with margin top, we just push the problem down to the second line.

**Comment by daveliepmann** [comment]
Thanks for raising this point. AFAICT all potential solutions would require radical changes. For that reason it's unlikely that I will take the time to address this. If anyone sees a way to solve it, please open a PR, but I can't promise fast response times or even that a solution that makes major changes will be merged.

**Comment by uhoreg** [comment]
I think that setting margin-top of the sidenotes/marginnotes to 0.3rem would be an improvement to the current situation.  It's true that it doesn't fix the issue completely, since the second line would be misaligned, but it would solve the issue for single-line notes, and would be no worse than the current situation.  If a PR that makes that change has a chance of getting accepted, I'd be happy to open a PR.

**Comment by daveliepmann** [comment]
@uhoreg A PR with that change would be very welcome. I just checked my copy of The Visual Display of Quantitative Information, in which the solution seems to be to line up the first line of a sidenote with the body text:

<img width="918" alt="Screen Shot 2019-09-07 at 12 26 35 PM" src="https://user-images.githubusercontent.com/974443/64473765-268d2180-d16b-11e9-9361-ca11eca00982.png">
<hr/>

...with no attempt to align the baseline of sidenotes' second and further lines:

<img width="1143" alt="Screen Shot 2019-09-07 at 12 27 29 PM" src="https://user-images.githubusercontent.com/974443/64473764-1ffeaa00-d16b-11e9-8674-e100f589c0fd.png">

So at least on the surface, I think your approach may be the most orthodox Tufte approach.
