### ISSUE TITLE
font size of sidenote numbers is mismatched between main text and sidenote

### ISSUE THREAD

**Issue by uhoreg** [edwardtufte/tufte-css#135]
The sidenote numbers are bigger than the corresponding number in the main text.  The sidenote font size is 1.1rem, and the number in the main text is 1.0rem.
![image](https://user-images.githubusercontent.com/1012976/43612929-c8e085ac-967b-11e8-8781-2a17a068e9c4.png)
This can be fixed by adding `font-size: 1rem` to the `.sidenote:before` rule.
![image](https://user-images.githubusercontent.com/1012976/43613106-40aa8f24-967c-11e8-97c1-64a27101a947.png)

**Comment by daveliepmann** [comment]
Thanks for reporting this—good catch. A pull request fixing it would be welcome. Please see the [contribution guidelines](https://github.com/edwardtufte/tufte-css#contributing). I'm heading on vacation so it won't get merged for some weeks.
