### ISSUE TITLE
Special underlining logic no longer necessary?

### ISSUE THREAD

**Issue by rtm** [edwardtufte/tufte-css#137]
Chrome (and other browsers I think) now underline more intelligently, so the special-casing of underlining is not just unnecessary, depending on your point of view it's actually intrusive. Perhaps the time has come or will soon come to get rid of it. Meanwhile, I have found that this works:

    a:link { all: unset; }

And then putting back underlines yourself with `text-decoration` if you want.

**Comment by daveliepmann** [comment]
>Chrome (and other browsers I think) now underline more intelligently,

Is there a chart of browser support for underlining that clears descenders? I can't find one on a quick search, and last I heard support was on its way but not arrived. (The quality of that support would also have to compare favorably to our current approach.)

Tufte CSS is happy with the current approach until the feature is supported widely across browsers. Just Chrome support is unsatisfactory for our purposes.

**Comment by gerwitz** [comment]
I'm adding to this thread only to caution against confusing "support for underlining that clear descenders" with support for `text-decoration-skip-ink`. I believe Safari desktop and mobile do not yet support this, yet their default behavior elegantly renders without clashing with descenders.

**Comment by otherjoel** [comment]
> Is there a chart of browser support for underlining that clears descenders? 

https://caniuse.com/#feat=text-decoration — note footnotes 3, 4, and 5

**Comment by daveliepmann** [comment]
Thanks for the link, Joel. Closing this for now. The time is soon but not now. Let's all keep an eye on browser support for descender-clearing both by default and through `text-decoration-skip-ink`, and either comment here or open a new issue or PR when such a solution is available.

**Comment by waldyrious** [comment]
For reference, the browser support information for `text-decoration-skip-ink` can be checked directly at caniuse: https://caniuse.com/#feat=mdn-css_properties_text-decoration-skip-ink (although the data comes from MDN).
