### ISSUE TITLE
Issues with ePub

### ISSUE THREAD

**Issue by benofben** [edwardtufte/tufte-css#139]
Your project seems really cool, but it renders poorly with ePub.  I realize that's probably outside the scope of what you're trying to do, but it was a bit of a bummer.  Here's an example:

![image](https://user-images.githubusercontent.com/8282917/46590838-7222e100-ca6b-11e8-8c18-8932fa7d16e6.png)

and another:

![image](https://user-images.githubusercontent.com/8282917/46590841-79e28580-ca6b-11e8-9ffc-e8812c52164c.png)

and my code underlying it (see build.sh to output the ePub):
https://github.com/benofben/the_intelligent_property_investor/tree/bea1cd20527e5dd782a07af0e6089061fa1fd9db

**Comment by daveliepmann** [comment]
I appreciate the report but I'm afraid you're right, this is out of scope. Thanks.
