### ISSUE TITLE
No tag for v1.7.1

### ISSUE THREAD

**Issue by wolfgang42** [edwardtufte/tufte-css#147]
It looks like the latest commit bumps the version to 1.7.1, but the last tagged release is 1.7.

**Comment by daveliepmann** [comment]
My bad. Try now: https://github.com/edwardtufte/tufte-css/releases/tag/v1.7.1

**Comment by wolfgang42** [comment]
Thanks!

**Comment by daveliepmann** [comment]
I'll close the ticket, but please comment here or in a fresh issue if you run into similar trouble in the future. Thanks again for letting me know so I could fix it.
