### ISSUE TITLE
Remove underline in link when using icon

### ISSUE THREAD

**Issue by torkar** [edwardtufte/tufte-css#150]
@daveliepmann, I think you know the answer to this question.

I want to remove the underline when I use an icon with a link in `tufte-css`. See the three svg icons at the top of the page here: http://www.torkar.se

I’ve used the usual: style="text-decoration:none” and also tried to set the border to 0, but I have a feeling `tufte-css` is the issue here? Greatly appreciate any tips since I've never played with `css`.

Thanks a lot for creating the `css` and allowing us to use Tufte's ideas on the web!

**Comment by daveliepmann** [comment]
Hi, thanks for reporting this. 

You're right that `text-decoration` would normally be a solution, but Tufte CSS does some hacky stuff with `background` and `text-shadow` to get fancy underlines. The details start at [this line](https://github.com/edwardtufte/tufte-css/blob/c414b9117d5b39bdb747a172822333fc1043aee3/tufte.css#L232), but aren't necessary to understand. Instead, the recommended way to prevent Tufte CSS default underline behavior is to use the `no-tufte-underline` class (defined [here](https://github.com/edwardtufte/tufte-css/blob/gh-pages/tufte.css#L225)) on your anchor tags. 

For example, the first one should be like this:

```
<a class="no-tufte-underline" href="https://twitter.com/rtorkar" style="border:0;">
     <img src="img/twitter.svg" alt="Twitter" style="width:18px;height:18px;border:0;">
</a>
```

Hope this helps.

**Comment by torkar** [comment]
Thanks for the answer!

**Comment by waldyrious** [comment]
> Tufte CSS does some hacky stuff with `background` and `text-shadow` to get fancy underlines.

Just linking the relevant issue, for cross-reference: https://github.com/edwardtufte/tufte-css/issues/137
