### ISSUE TITLE
div > pre > code not so good

### ISSUE THREAD

**Issue by fulldecent** [edwardtufte/tufte-css#157]
I am using the following code for my code snippets:

```css
div > pre > code
```

 The result is that an extra-wide box appears, which is suboptimal.

<img width="1552" alt="Screen Shot 2020-07-22 at 11 56 33" src="https://user-images.githubusercontent.com/382183/88199262-9b960800-cc12-11ea-8277-66779f8dcba6.png">

**Comment by daveliepmann** [comment]
Is there a `section` wrapping that `div`? From the demo/usage document:

>Organize your document with an `article` element inside your `body` tag. Inside that, use `section` tags around each logical grouping of text and headings.

It would be helpful to share a minimal example as text, so the issue can be easily reproduced.

**Comment by fulldecent** [comment]
Minimal example:

https://jsbin.com/varukulesi

**Comment by daveliepmann** [comment]
This appears to be a function of third-party code highlighting the `pre` rather than the `code`.

**Comment by daveliepmann** [comment]
@fulldecent Any further findings on this?

**Comment by fulldecent** [comment]
Yes, the highlighter was styling the div.

I did this workaround for [Rogue](https://github.com/rouge-ruby/rouge).

```css
.highlight {
  background: none
}
```

But that is out of scope for this project so I'll call this an incompatibility of Rogue with tufte.css's wide block approach.
