### ISSUE TITLE
navbar support/advice?

### ISSUE THREAD

**Issue by pdelfino** [edwardtufte/tufte-css#162]
Hi guys,

I really like this CSS work. Congratulations on doing such a good job! I am using it to build a simple and personal blog.  You guys can [check it out here](http://www.pdelfino.com.br).

I would like to add a navbar. By the way, a minimalistic one. Usually, people go with Home and About. In my case, I am doing just Home. 

I added this to the CSS file:

```
  .home {
    position: absolute;
    right: 300px;
    top: 0px;
    font-weight: 400;
    margin-top: 2rem;
    margin-bottom: 1.5rem;
    font-size: 2rem;
    line-height: 1;
    z-index: 10000;
  }
```

This is the final result:
![Screenshot from 2021-01-17 16-41-55](https://user-images.githubusercontent.com/7698207/104853957-0040cf80-58e3-11eb-940e-0fe3d8b51c3a.png)

Have you guys ever thought about adding a navbar?
Would you do something different than I did?

This is my first project in web development. Sorry for the eventual mistakes or the absence of design skills/good taste.

**Comment by carbontwelve** [comment]
The following websites use Tufte CSS and have settled on a top navbar like yourself:

[jeffrafter.com](https://jeffrafter.com/)
![image](https://user-images.githubusercontent.com/464699/122748937-a757d780-d284-11eb-8bc3-451c31a959ed.png)

[marchie.io](https://marchie.io/)
![image](https://user-images.githubusercontent.com/464699/122749043-c7879680-d284-11eb-8ecd-7e222c6c2075.png)

[jordanrhea.com](http://jordanrhea.com/)
![image](https://user-images.githubusercontent.com/464699/122749213-f7cf3500-d284-11eb-8a99-305b684bbd8d.png)

This website has a left side bar navigation and uses Tufte CSS for the main content styling:
[kineticgraphs.org](https://kineticgraphs.org/)
![image](https://user-images.githubusercontent.com/464699/122749355-25b47980-d285-11eb-8505-75b4366b653e.png)

Finally this website make use of Tufte CSS but has no global navigation, instead choosing to have the website name link back to the homepage from every subpage.
[micahlerner.com](https://www.micahlerner.com/)
![image](https://user-images.githubusercontent.com/464699/122749572-68765180-d285-11eb-9bbf-1af6164db561.png)
![image](https://user-images.githubusercontent.com/464699/122749616-76c46d80-d285-11eb-84dc-e1f38d0b37e9.png)

Hopefully these options help.
