### ISSUE TITLE
links look weird when highlighted

### ISSUE THREAD

**Issue by bionicles** [edwardtufte/tufte-css#163]
![image](https://user-images.githubusercontent.com/24532336/114320718-445bfe80-9ae5-11eb-985e-1cc0f8ccb5fa.png)

i discovered the issue is here, because if we view page source and comment out this section, it stops happening
```
a:link, .tufte-underline, .hover-tufte-underline:hover {
    text-decoration: none;
    background: -webkit-linear-gradient(#fffff8, #fffff8), -webkit-linear-gradient(#fffff8, #fffff8), -webkit-linear-gradient(currentColor, currentColor);
    background: linear-gradient(#fffff8, #fffff8), linear-gradient(#fffff8, #fffff8), linear-gradient(currentColor, currentColor);
    -webkit-background-size: 0.05em 1px, 0.05em 1px, 1px 1px;
    -moz-background-size: 0.05em 1px, 0.05em 1px, 1px 1px;
    background-size: 0.05em 1px, 0.05em 1px, 1px 1px;
    background-repeat: no-repeat, no-repeat, repeat-x;
    text-shadow: 0.03em 0 #fffff8, -0.03em 0 #fffff8, 0 0.03em #fffff8, 0 -0.03em #fffff8, 0.06em 0 #fffff8, -0.06em 0 #fffff8, 0.09em 0 #fffff8, -0.09em 0 #fffff8, 0.12em 0 #fffff8, -0.12em 0 #fffff8, 0.15em 0 #fffff8, -0.15em 0 #fffff8;
    background-position: 0% 93%, 100% 93%, 0% 93%;
}
```

next i went through and commented out each line. the issue was here:
```
     text-shadow: 0.03em 0 #fffff8, -0.03em 0 #fffff8, 0 0.03em #fffff8, 0 -0.03em #fffff8, 0.06em 0 #fffff8, -0.06em 0 #fffff8, 0.09em 0 #fffff8, -0.09em 0 #fffff8, 0.12em 0 #fffff8, -0.12em 0 #fffff8, 0.15em 0 #fffff8, -0.15em 0 #fffff8;
```

![image](https://user-images.githubusercontent.com/24532336/114320857-001d2e00-9ae6-11eb-9c08-e4ac486e0036.png)

**Comment by carbontwelve** [comment]
The text shadow is there to provide the correct gap between the letters and their underline, the underline is being provided by use of a background gradient technique.

The best way to solve the issue you have raised is using the `::selection` [pseudo-element](https://developer.mozilla.org/en-US/docs/Web/CSS/::selection) like so:

```css
a::selection{
    text-shadow: none;
}
```

**Comment by daveliepmann** [comment]
Closing this because the weird look is a necessary side effect of desired behavior.
