### ISSUE TITLE
Inconsistent spacing due to inline labels as sidenote numbers

### ISSUE THREAD

**Issue by AB1908** [edwardtufte/tufte-css#167]
<img width="655" alt="image" src="https://user-images.githubusercontent.com/14124383/128579230-d0c75bbc-5cc3-434f-9d8f-e15134a10024.png">
We can clearly see that the line containing a sidenote has inconsistent line height. It is quite annoying, especially on mobile. We can see it even more clearly if we highlight the lines like so:
<img width="641" alt="image" src="https://user-images.githubusercontent.com/14124383/128579276-73d83d21-5443-4452-b5dd-c1f4556efd31.png">

**Comment by daveliepmann** [comment]
Good catch, let's fix this.
