### ISSUE TITLE
Anything in the margin disappears with narrow browser window

### ISSUE THREAD

**Issue by nelscity** [edwardtufte/tufte-css#176]
Margin notes, margin images, and side notes just go away completely when narrowing the window, whereas I would expect them to fall in line or something else.

**Comment by ttmc** [comment]
I thought the same thing at first, but if you read [the explanation demo page](https://edwardtufte.github.io/tufte-css/), that's on purpose.

If you want to read a sidenote (i.e. with a superscript numeral), you click or tap the associated superscript numeral and the "sidenote" will appear below. If you want to read a margin note, you click or tap the ⊕ symbol.

**Comment by daveliepmann** [comment]
That's correct, thanks for explaining
