### ISSUE TITLE
Underlines missing at certain zoom levels

### ISSUE THREAD

**Issue by AB1908** [edwardtufte/tufte-css#179]
I have a few more custom settings so in case you can't repro this, I'd be happy to add them here.

This is at 90% zoom:
![image](https://user-images.githubusercontent.com/14124383/157427301-d27528ad-c588-4a51-97a1-12a42beb1875.png)

100% zoom:
![image](https://user-images.githubusercontent.com/14124383/157427415-a4221c59-b029-44b7-b0da-540fe76f8ef5.png)

Strangely, it's back on 80% zoom:
![image](https://user-images.githubusercontent.com/14124383/157427495-da925d92-1657-4531-81dd-622653993ab1.png)

**Comment by bueltge** [comment]
Which browser do you use? 

In Chrome Version 102.0.5005.63 , Windows system still works at 90 % zoom level
![image](https://user-images.githubusercontent.com/133425/172827667-3f8a1269-170d-4354-aa3c-5e886d9a9295.png)

Also in MS Edge Version 102.0.5005.63 , Win, 90%
![image](https://user-images.githubusercontent.com/133425/172827851-2392ed6f-0b45-445e-8c25-718b904241cd.png)

**Comment by AB1908** [comment]
My apologies, this is Firefox on Windows 10 at 1366x768.

**Comment by bueltge** [comment]
Can you validate the problem? Another client or update, restart with your machine?

**Comment by AB1908** [comment]
Yes, gladly. Can you give me a list of test cases? I have a single 1366x768 monitor with both Windows and Arch Linux, Firefox and Chromium on each. I'll list those and you can let me know if there's anything more you want me to test out.

**Comment by bueltge** [comment]
Not really. I mean, no other one has the problem. So you should try them on several clients, screens and browsers to identify the problem. We have the question in this case - it is a problem on your side or on the CSS file of the solution?

**Comment by AB1908** [comment]
You're right, I had some custom settings that got in the way. I cannot replicate the issue on Firefox (101.0.1 (64-bit)) at 100%, 110%, 90% zoom levels or on Chromium (Version 102.0.5005.115 (Official Build) Arch Linux (64-bit)). Instead, I have a setting `layout.css.devPixelsPerPx` in Firefox that lets me adjust DPI. I use it since my screen is both small and low resolution and zooming out only changes web page rendering and not the appearance of Firefox as a whole. I use `0.85` as the set value and the default is `-1`. Using the default setting makes the problem disappear.

**Comment by bueltge** [comment]
So the resulting problem is in depending on your additional stylesheet, and we should close this issue, because there is no problem at the solution. Thanks for clarify this @AB1908 !

**Comment by AB1908** [comment]
It's not an additional stylesheet but an advanced setting in Firefox configured via `about:config`. Nonetheless, I'll be closing the issue.
