### ISSUE TITLE
Darkmode background is too dark

### ISSUE THREAD

**Issue by richardanaya** [edwardtufte/tufte-css#182]
I suggest you use the color `Eigengrau` "The dark grey colour seen by the eyes in perfect darkness as a result of signals from the optic nerves" . 

#16161d

**Comment by richardanaya** [comment]
Current Color (#151515)
<img width="188" alt="Screenshot 2023-03-05 at 8 03 50 PM" src="https://user-images.githubusercontent.com/294042/223017037-7f035a89-ecd9-4269-a844-d112fc995ce2.png">

Eigengrau vs Black
![image](https://user-images.githubusercontent.com/294042/223016921-8a8e988a-fcc3-44b7-920b-7ad6dfc0d514.png)

**Comment by daveliepmann** [comment]
I like Eigengrau a lot, and I think I would usually prefer it over `151515` in a vacuum. However 1. that's not reason enough to overcome inertia of what exists and 2. I feel like the color @mailtokamalnayan chose is a better analogue to `fffff8`? I'm open to being convinced but don't have bandwidth to participate in extended discussion. Closing this for now but please feel free to write up an argument.
