### ISSUE TITLE
Academicicons are very strangely underlined

### ISSUE THREAD

**Issue by ulbrichdennis** [edwardtufte/tufte-css#185]
Hi,

I am using tufte-css for my
[website](https://www.dulbrich.de).

On my page called "Home"  (at its end), I am using Academicicons to link to my arXiv profiles etc.

Unfortunately, the icons are very strangely underlined and I have tried a lot and also did a lot of google searches.

The usual answer there is to do

```
a:link{
text-decoration: none !important;
}
```

but this does not work.

Therefore, I think that maybe my problem has something to do with the specific design of tufte-css.

Did you experience something similar and maybe have an idea how to overcome this issue?

Best!

**Comment by torkar** [comment]
I don't have underlined icons on my page (at the top): www.torkar.se

I use this:
`<a class="no-tufte-underline" href="https://scholar.google.se/citations?hl=en&user=yNR3XUMAAAAJ&view_op=list_works&sortby=pubdate"
                    style="border:0;">
                    <img src="img/scholar.png" alt="Google Scholar" style="width:22px;height:22px;border:0;"></a>`

**Comment by ulbrichdennis** [comment]
@torkar I don't know why but it works! Thanks a lot!

**Comment by ulbrichdennis** [comment]
Solved
