### ISSUE TITLE
Descenders for link underlines are now available without the text-shadow hack

### ISSUE THREAD

**Issue by WebBurnout** [edwardtufte/tufte-css#186]
Hey, it's 2024 and the `text-decoration-skip-ink` property is [now >93% supported](https://caniuse.com/mdn-css_properties_text-decoration-skip-ink). The current implementation has cause quite a few issues in the past: https://github.com/edwardtufte/tufte-css/issues/163 https://github.com/edwardtufte/tufte-css/issues/179 https://github.com/edwardtufte/tufte-css/issues/49 https://github.com/edwardtufte/tufte-css/issues/86 https://github.com/edwardtufte/tufte-css/issues/96

Maybe it's time to use this property instead of the workaround?

**Comment by daveliepmann** [comment]
PR welcome
