### ISSUE TITLE
Sparklines

### ISSUE THREAD

**Issue by daveliepmann** [edwardtufte/tufte-css#22]
Point to JavaScript resources for sparklines support in the documentation.

**Comment by TDaltonC** [comment]
I made a pull request for this. The libraries are abandoned, but they look like they still work.

**Comment by daveliepmann** [comment]
Thanks @TDaltonC !

I added a paragraph in the demo doc `index.html`, too. I'd like to be able to specifically recommend one, or describe the pros and cons of each for different applications, but without using them for an actual project I can't do so. I'm going to close this issue for now, with the caveat that further work would still be appreciated.
