### ISSUE TITLE
Leading of sidenotes is too great

### ISSUE THREAD

**Issue by godbyk** [edwardtufte/tufte-css#29]
With the smaller typeface, the line-spacing should also be less than that of the main text.

**Comment by daveliepmann** [comment]
I tweaked the line height in https://github.com/daveliepmann/tufte-css/commit/6aca33a664100669372e7bab0fbff8ad9c42160a — further details or a PR would be appreciated.

**Comment by godbyk** [comment]
I'd try 1.4. It's a bit tighter, but I think it still looks good.

The only nit-pick I have then is that the baselines of the sidenote and the main text aren't aligned with one another (both blocks are top-aligned). I'm afraid I don't know enough of CSS to know how to fix this, though. Perhaps there's a zero-width character that we can prepend to the sidenote that is the same size as the body text to force the baseline lower?

**Comment by jabyrd3** [comment]
^ i was just about to post an issue about this. The baseline of the first line of the sidenote needs to be aligned with the baseline of the sentence it's being pulled from. Great work though, this stylesheet is awesome!

**Comment by jjsanderson** [comment]
For clarification, I appled:

```
.sidenote, .marginnote { line-height: 1.4; padding-top: 0.4rem; }
```

…which eyeballs about right to me. I checked alignment briefly using [Xscope](http://xscopeapp.com), but haven't tested exhaustively.

**Comment by daveliepmann** [comment]
Per Edward Tufte, sidenote `line-height` is `1.3` as of 3aa48b4ac13cfe1e323e4547844eee555edc4703. You were right!
