### ISSUE TITLE
Example using tufte-css with Jekyll/GitHub pages?

### ISSUE THREAD

**Issue by peterjc** [edwardtufte/tufte-css#31]
This is a wishlist issue, but I can't be the only person thinking this could make the basis of a very elegant Jekyll template style for using GitHub pages: https://help.github.com/articles/using-jekyll-with-pages/

**Comment by peterjc** [comment]
This overlaps somewhat with #21

**Comment by daveliepmann** [comment]
Clay Harmon has done some work [here](https://github.com/clayh53/tufte-jekyll), though it may be based on an older version of Tufte CSS.

**Comment by daveliepmann** [comment]
Ping @clayh53 :)

**Comment by ghost** [comment]
See also:
- https://github.com/mandaris/TuftePelican
- https://github.com/profedrini/nikola-tufte
- https://github.com/bobdenotter/bolt-tufte-theme
- https://github.com/0atman/caddy-tufte-blog
- https://github.com/dvdhllbrg/tufte-ghost
- https://github.com/adelq/tufte-ghost
- https://github.com/popopome/pollentufte

It might be good to start a static-site theme thread to collect `tufte-css` versions for different site generator apps.

**Comment by mandaris** [comment]
I'm far from complete with my implementation. This is my first "design" project. 

Definitely a slow labor of love.

**Comment by clayh53** [comment]
Just noticed this issue post. FWIW, I synced up the tufte-jekyll theme to the  current tufte-css version a month or so ago. The only thing I think that remains is renaming the font files to conform with the new naming. It has Mathjax integration as well.

And it works fine with github pages. It includes a rakefile to push the finished site to a gh-pages branch. I use it to keep the demo site in sync.
