### ISSUE TITLE
font size in lists

### ISSUE THREAD

**Issue by neuwirthe** [edwardtufte/tufte-css#32]
Ordere and unordered lists use much smaller fonts on wide screens. When I want to use this as a means to structure text, this does not look so nice. I there a way to couple the font size used in lists to the font size used by the plain html document body?

**Comment by daveliepmann** [comment]
I simply omitted/didn't get to styling `<ul>` and `<ol>` tags yet. Adding CSS for those in the tufte.css file should be straightforward. 

One of my concerns is that bullet points may be the wrong tool for the kind of writing we want to do with Tufte CSS. I think we should do the basic work of aligning font sizes for lists with other text. In the future we may want to add some design guidelines to the demo doc, describing when to reach for lists and when not to.

**Comment by daveliepmann** [comment]
Addressed by https://github.com/daveliepmann/tufte-css/commit/aec343461a12d37cb1db9f048c02a7c274c5205c

**Comment by neuwirthe** [comment]
Dave,
I am using a modified version f tight.css and I am quite happy with your project as base ;-)

I  also understand why, given Tufte’s rants about Powerpoint, bulleted lists are not top priority.

But if you have time to spare, take a lookout www.wahlanalyse.com http://www.wahlanalyse.com/
(possibly with google translate as your friend)

I have a paragraph:
The main results are
*
*

and I think that for such a summary bulleted lists still are a good way
of presentation.

So, if you make them part of the basic mechanisms you supply,
that would be helpful.

Regards

Erich

**Comment by daveliepmann** [comment]
That wahlanalyse site looks very cool, Erich. I like what you've done with the styling.

I agree that summarizing results can be an effective and correct use of bulleted lists. Part of my reason to default to no-bullets is to get users to take a second look at the principles involved.
