### ISSUE TITLE
code classes in headings are too tiny

### ISSUE THREAD

**Issue by fasiha** [edwardtufte/tufte-css#33]
Using `<span class="code">` inside `h1` makes the code text tiny, because of `font-size: 1rem;` for `.code`. What are the advantages of this versus using a percent `90%` or replacing `rem` with `em`?

**Comment by daveliepmann** [comment]
The only reason this has not been an issue is that I have not yet used the `code` class inside an `h1` element. I'm not aware of any particular design decision favoring rem over percentages in this case. I don't recall the design decision around `rem` versus `em`, but it should be in the commit history (circa Clay Harmon's contributions?) 

If you can optimize `code` inside of headers without affecting the sizing of `code` elsewhere, that would be a welcome pull request. That might mean a rem/em/% switch as described above, or it might mean just adding a rule for `span.code` within h1, h2, and h3 elements.

**Comment by fasiha** [comment]
Thanks to your detailed advice it was easy to make pull request #35 :smile:

**Comment by daveliepmann** [comment]
:+1:
