### ISSUE TITLE
The figures should be SVG

### ISSUE THREAD

**Issue by kevinmarks** [edwardtufte/tufte-css#34]
Using PNG for the figures is not working with Tufte's intent, as then they are not attuned to the possibilities of the display. 
Also, figure 3 is not constrained to the width of the text; it pokes out inot the margins too. In addition, it is a style of plot that Tufte explicitly condemns on page 125 of The Visual Display of Quantitative Information:
![img_20150807_094315](https://cloud.githubusercontent.com/assets/99008/9140886/480410aa-3ce9-11e5-8f1b-d7c4b8670761.jpg)

**Comment by daveliepmann** [comment]
OK. Pull requests welcome. The figures are just for demonstrative purposes, so if you could spin up some data-backed SVGs that would be swell. 

As for replacing figure 3, again, pull requests are welcome. The purpose of that figure is not to convey the data, but to serve as an example of fitting a figure into the flow of the text.

**Comment by daveliepmann** [comment]
Mr. Tufte requested that we use some specific example figures from his texts, which we've done, so I'm closing this for now. I suppose I'm still open to seeing the results of converting those PNGs to SVG, but I can't promise we'd use them.
