### ISSUE TITLE
Something wrong with the centering on Firefox 39.0.3/Linux

### ISSUE THREAD

**Issue by tripzilch** [edwardtufte/tufte-css#38]
Screenshot: http://i.imgur.com/8t95PQS.png

Something similar happens with the full-width image.

Chromium looks fine.

**Comment by vyp** [comment]
I get the same effect (firefox 39.0.3 too). If it helps, I remember when I initially saw the page a few days ago, I didn't see this, so I'm guessing it must be a change to the site in this time. Although, I also think I upgraded from firefox 39.0 to 39.0.3 in this time too. So perhaps someone may want to test on firefox 39.0.

**Comment by godbyk** [comment]
I know the centering for the booktabs-style table is a bit wonky. I mentioned that in my pull request. I just don't know enough css to fix it. In my version of Chromium it's off-center a little bit, but not nearly as exaggerated as the screenshot shows.

**Comment by daveliepmann** [comment]
Should be fixed by https://github.com/daveliepmann/tufte-css/commit/f5d164ae8c12446c71d6b69b786905b657154ca9

**Comment by vyp** [comment]
Yes, it looks good to me. :+1:
