### ISSUE TITLE
sidenote should make use of <sup> element

### ISSUE THREAD

**Issue by soenkekluth** [edwardtufte/tufte-css#40]
`<sup> <a href="#idOfSiteNode">3</a> </sup> ...... <span id="idOfSiteNode">description</span>`

**Comment by daveliepmann** [comment]
I think we switched away from `<sup>` in Pull #14. Personally I'd prefer `<sup>` to the generic `<span>`.

**Comment by bjornmeansbear** [comment]
would it also make semantic sense to wrap the actual note texts in `<aside>` tags instead of spans?

**Comment by daveliepmann** [comment]
@bjornmeansbear Semantically, yes, practically no. See https://github.com/daveliepmann/tufte-css/issues/24#issuecomment-128699026

**Comment by bjornmeansbear** [comment]
@daveliepmann sorry, I did what I find frustrating elsewhere — just offering up some thinking without actually having looked at the problem.

**Comment by daveliepmann** [comment]
Another thought: I think `<sup>` is correct for sidenote references, but not for margin note references. Additional complexity to consider! :)

**Comment by bjornmeansbear** [comment]
I think that `<sup>` is merely for anything you want in superscript and is agnostic to if its a sidenote, footnote, etc. 

It's like `<em>` or `<strong>` or `<b>` or `<i>` — a way to add semantic and stylable typographic hierarchy. 

from W3C:
The `<sup>` element represents a superscript. This element must be used only to mark up typographical conventions with specific meanings.
http://www.w3.org/wiki/HTML/Elements/sup

from MDN:
The HTML Superscript Element (`<sup>`) defines a span of text that should be displayed, for typographic reasons, higher, and often smaller, than the main span of text.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/sup

from sitepoint: 
This element can be applied to any text content, but its use is likely to be limited to footnote and mathematical applications.
http://reference.sitepoint.com/html/sup

**Comment by mandaris** [comment]
I was looking at this issue and was wondering why you don't use `<aside>`?

From MDN:
The HTML `<aside>` element represents a section of the page with content connected tangentially to the rest, which could be considered separate from that content. These sections are often represented as sidebars or inserts. 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/aside

Sure it's not 100% syntactic but it makes more sense than making a span jump out from a `<p>`... to me at least.

**Comment by daveliepmann** [comment]
@mandaris I believe my comment above, and the link in it, addresses your question: https://github.com/edwardtufte/tufte-css/issues/40#issuecomment-131116117

It's unclear to me what using `<aside>` adds, and it is just as wrong to have `<aside>` within a `<p>`, no?

**Comment by reitzig** [comment]
@daveliepmann Using `<aside>` would add semantics. For instance, you could filter out all "aside" content -- sidenotes, marginnotes, footnotes, ... -- with a single, semantic CSS directive where needed, e.g. for post excerpts.

It can't be used reasonably for specifying sidenotes in the middle of a paragraph since `<aside>` is a block tag. We'd need a span-equivalent for `<aside>`. Too bad.
