### ISSUE TITLE
Example of tufte-css in the wild

### ISSUE THREAD

**Issue by ghost** [edwardtufte/tufte-css#41]
link removed

Thanks again for the good base on which to build. :+1: :cake:

**Comment by hhboltz** [comment]
It's not an example of vanilla tufte-css, but I use tufte-css for this (mostly german, still got work to do) http://t1.physik.tu-dortmund.de/~boltz/  Its a somewhat atypical usage and I did some changes, but maybe you have use for it. The one tufte-compliant change might be the styling of h1 (sans-serif, grayish, same as book title in tufte-book)

**Comment by daveliepmann** [comment]
Let's combine this issue with https://github.com/edwardtufte/tufte-css/issues/26 — more examples welcome! :)
