### ISSUE TITLE
Don’t put figure in a p.

### ISSUE THREAD

**Issue by Zegnat** [edwardtufte/tufte-css#42]
> Besides margin and full width figures, you can of course also include figures constrained to the main column. You’re going to have to police yourself with the size of any images. <b>Wrap the `figure` tag in a paragraph tag.</b> Any label or margin note goes in a figcaption tag inside the figure. <i>[Emphasis mine.]</i>

This seems wrong. The `figure` element is not an inline element (“phrasing content”) and is not allowed inside a paragraph element at all. In fact, browsers will simply correct the DOM:

![Screenshot: DOM as created by Safari.](https://cloud.githubusercontent.com/assets/490579/9273769/f6e87948-428f-11e5-8b49-2904e97dffa5.png)

Is there any reason the CSS needs the `figure` to be inside the `p`? It doesn’t look like it, but I have no time to test right now. Otherwise, just remove that line from the website.

**Comment by daveliepmann** [comment]
I agree that it's wrong. The reason is that non-full-width figures in the main body of the text need to be constrained to the same boundaries as paragraphs. A `div` with a container class made to match the dimensions of `p` is needed.

**Comment by Zegnat** [comment]
> The reason is that non-full-width figures in the main body of the text need to be constrained to the same boundaries as paragraphs.

Ah, gotcha! But as most current browsers correct the DOM as shown in my initial post, you aren’t containing it to the same boundaries at all and the `p` might as well be left out of it completely.

![Screenshot: Safari displaying a non-full-width figure breaking paragraph width.](https://cloud.githubusercontent.com/assets/490579/9275676/06690766-429f-11e5-9b5e-1bd5fdc68f3f.png)

Is there any reason to not set the width on `figure` directly?

**Comment by daveliepmann** [comment]
See https://github.com/daveliepmann/tufte-css/commit/29d1e3c5a820835a8ddf029352c6a6f1090139eb

The bigger problem now is positioning `figcaption`. Help on that would be appreciated.
