### ISSUE TITLE
`figcaption` positioning is wack

### ISSUE THREAD

**Issue by daveliepmann** [edwardtufte/tufte-css#44]
Figure captions, inside `figure` tags, are not positioning properly under a variety of viewports.

**Comment by Zegnat** [comment]
I think I am going to have a good look at this later tonight when my schedule clears up. It would be really great to get this solved, as we might be able to repurpose it for tables as well! (No more `div`s!)

> When a `table` element is the only content in a `figure` element other than the `figcaption`, the `caption` element should be omitted in favor of the `figcaption`.

From [4.9.2 The `caption` element](http://www.w3.org/TR/html5/tabular-data.html#the-caption-element), HTML5 spec.

**Comment by daveliepmann** [comment]
:+1:

**Comment by Zegnat** [comment]
I have made a start at [Zegnat/tufte-css](https://github.com/Zegnat/tufte-css/tree/figures), but it is extremely crude. Feel free to take a look and see if it sparks any ideas for you. It does somewhat support <720 pixels wide, but vertical margins are still off.

**Comment by daveliepmann** [comment]
https://github.com/daveliepmann/tufte-css/commit/a72d0c3c8092b46dae700fb6317fa11ef7f40359 addressed the immediate egregious errors that were evident on small screens. A more comprehensive solution is still desired.

**Comment by daveliepmann** [comment]
It would also be of value for me to reread Tufte to take in some of his examples of figures. On a quick skim of The Visual Display of Quantitative Information, I notice many figures actually have no label, since they are introduced in the text. Figure captions in the margin seem restricted to citations that he doesn't introduce in the main body of the text. Sometimes these are aligned with the bottom of the figure, sometimes with the top, according to what is most pleasing to the eye. Again, more rigor and study is required.

**Comment by Zegnat** [comment]
`figcaption` is not required inside `figure` from an HTML point of view, so optional labels shouldn’t really be a problem. A choice of aligning with top or bottom might be harder to work with in CSS…

**Comment by crmackay** [comment]
you can have the figure caption above or below the image simply by placing the `<figcaption>` element ahead of the `<img />` in the document, as opposed to after it. Here is code pen: http://codepen.io/crmackay/pen/yNdyXz?editors=110

**Comment by bolatovumar** [comment]
@daveliepmann could you post examples of this issue?

**Comment by daveliepmann** [comment]
@bolatovumar The essential problem is that `figcaption` does not now and has never in the past successfully created captions that are aligned identically to sidenotes or margin notes. There's always been at least a tiny discrepancy on all viewports. I've removed uses of and references to `figcaption` because of this issue. If we can get them _identical_ to marginalia then they'll be reintroduced, which I would like.

**Comment by RichardCore37** [comment]
Hi, I'm also having a problem with my figcaption displaying an unnecessary space above the text (or my image displaying an unnecessary space below the image. I've tried every fix that appears online - display block, vertical alignment, line heights, etc. but nothing seems to remove it!

**Comment by neillrobson** [comment]
Hey team! I've also run across these inconsistencies with `figcaption` styling. In my case, simply adding the following CSS _seemed_ to create pleasant, consistent styling between side-notes and captions for all viewports:

```css
figcaption {
  margin-right: -60%;
  width: 50%;
  margin-top: 0.3rem;
  line-height: 1.3;
  max-width: unset;
}

figure.fullwidth {
  display: inline-block;
}

figure.fullwidth figcaption {
  margin-right: 0%;
  float: none;
  width: auto;
  text-align: center;
}

@media (max-width: 760px) {
  figcaption,
  figure.fullwidth figcaption {
    margin-right: 0%;
    float: none;
    width: auto;
    text-align: center;
  }
}
```

A live demo of these adjustments can be found here: https://neillrobson.com/markdown-it-tufte/

**My design choices are purely subjective**, so I'd take no offense if you all say that this CSS isn't worth integrating into the main Tufte CSS library. (Local customizations what _cascading_ style sheets are for, after all!)

But if this little CSS patch does in fact solve the problems previously discussed in this issue thread, **I would happily open a PR** to get them integrated.

Thank you all so much for your work on this repository!
