### ISSUE TITLE
`subtitle` is not HTML

### ISSUE THREAD

**Issue by Zegnat** [edwardtufte/tufte-css#46]
[Line 15 of index.html](https://github.com/daveliepmann/tufte-css/blob/29d1e3c5a820835a8ddf029352c6a6f1090139eb/index.html#L15):

``` html
    <subtitle>Dave Liepmann</subtitle>
```

[According to HTML5Doctor](http://html5doctor.com/howto-subheadings/), reporting straight from the HTML5 spec, we should use `p` elements for subtitles:

``` html
    <header>
      <h1>Tufte CSS</h1>
      <p>Dave Liepmann</p>
    </header>
```

For clarity I would propose a class (`.subtitle`) rather than binding it to all paragraphs in headers (`header p`).

**Comment by daveliepmann** [comment]
Whoops. Thanks for the heads-up.
