### ISSUE TITLE
Smarter Link Underlines

### ISSUE THREAD

**Issue by jez** [edwardtufte/tufte-css#49]
It'd be awesome if Tufte CSS shipped with the kinds of underlines [described here](https://eager.io/blog/smarter-link-underlines/). He gives a simple Stylus mixin for how to do it reproducibly.

**Comment by daveliepmann** [comment]
There is some related discussion in Pull #43, including the link you cite. Great minds think alike, and obviously proper link underlining is a concern for lots of people.

I like the link style described in that page, but for the foreseeable future I am enforcing a strict no-additional-dependencies rule, and the pure-CSS version described in PR #43 still has some rough edges to fill out. 

I will try to add some language to `index.html` soon to indicate Eager.io's solution as an external resource for people who want more correct (but also more burdensome) link underlines.

**Comment by jez** [comment]
Oh, I didn't see one! (I just searched for `is:issue underline`, so it didn't turn up PR's).

**Comment by iDGS** [comment]
For anyone interested, here’s a direct link to the (IMHO) well-worth-a-read article about more lovely underlines on _Medium_: [https://medium.com/designing-medium/crafting-link-underlines-on-medium-7c03a9274f9](https://medium.com/designing-medium/crafting-link-underlines-on-medium-7c03a9274f9)

**Comment by daveliepmann** [comment]
We have switched to a CSS-only method of underlining that clears descenders. I appreciate everyone's input. I plan to incorporate some of the links @iDGS and @jez gave into the demo doc.
