### ISSUE TITLE
Firefox 41 large image displaced

### ISSUE THREAD

**Issue by mgraupner** [edwardtufte/tufte-css#53]
In Firefox 41 the image of Napoleon's March is overlapping with the Rhino in the sidenote.

![Screenshot](https://cloud.githubusercontent.com/assets/586644/10072042/d6deb0d2-62be-11e5-9b0e-0521c10ee1c3.png)

**Comment by crmackay** [comment]
i think I fixed this by adding `clear:both` to `.fullwidth` see pull request #54

**Comment by mgraupner** [comment]
I used @crmackay fix and added my own, perhaps someone can review this.
