### ISSUE TITLE
Info: Jekyll version of tufte-css

### ISSUE THREAD

**Issue by clayh53** [edwardtufte/tufte-css#58]
I have just finished modifying my [tufte-jekyll](https://github.com/clayh53/tufte-jekyll) repo to incorporate all the recent changes in the tufte-css. 

This Jekyll blog version allows a content creator to get all this yummy tufte-css look without having to write a bunch of complicated html. Instead, content is created using Markdown and some custom Liquid tags for the cool Tufte stuff.

There is a demo version [here](http://clayh53.github.io/tufte-jekyll/) if anyone would like to compare. I have made some modifications to the CSS to bring the typography into more of a Bringhurst-ian vertical scale. 

Any suggestions or help are welcome.

**Comment by ghost** [comment]
:+1: good work!!

**Comment by clayh53** [comment]
Yes, It makes the whole thing usable using Markdown and a few special Liquid tags. For instance:

```
## Some H2 Heading

Some content with [links](http://somewhere.com) and *emphasis* and **Strong**....
{% marginnote 'mn-id-1'  'Some Marginnote content *with* all the markdown goodness' %}

etc..
```

Is how content is created.

**Comment by ghost** [comment]
> I have made some modifications to the CSS to bring the typography into more of a Bringhurst-ian vertical scale. 

I looked through your documentation but could find no explanation of what you mean by this. I'm somewhat familiar with Bringhurst's work, but am curious what changes you made to achieve a "Bringhurst-ian" vertical scale.

**Comment by clayh53** [comment]
I have adjusted line heights on text elements using the techniques outline on [Web Typography](http://webtypography.net/2.2.2) so that all text elements have the same vertical rhythm. It amounted to small differences in headings and paragraphs, but where you really notice it is when you look at the longer sidenotes on both versions. You can slap a screen ruler between the paragraph text and the sidenote text, and the baselines on mine will align over multiple lines, where the tufte.css has tighter line spacing.

### tufte.css:

![tufte-css](http://clayharmon.com/img/tufte-sidenote.png)

### versus tufte-jekyll:

![tufte-jekyll](http://clayharmon.com/img/jekyll-sidenote.png)

**Comment by ghost** [comment]
Thanks for the explanation, and the image, that's helpful to see the difference. Do you think it would be good to pull your changes back into `tufte-css`?

**Comment by clayh53** [comment]
Personally, I think it looks a little cleaner that way. I'm not sure who the maintainer is now, but they of course are welcome to incorporate any changes that they feel are improvements.  I started with the tufte.css and scrubbed through all the text elements including table elements, list elements and blockquotes to put them all on the same vertical measure.

**Comment by ghost** [comment]
Cool. @daveliepmann is still the maintainer.

**Comment by devgru** [comment]
Great thing, :+1: for pulling changes into tufte-css, but not 'as is'. Looks like tufte.css can adopt this nice top navigation, credits footer and other blocks.

**Comment by crmackay** [comment]
The tufte-jekyll theme looks great! I'm working on a template/theme for [hugo](https://gohugo.io/) (another _en vogue_ static-site generator written in `go`).

However, I think the large leading on the sidenotes looks a bit off-putting. If you insist on maintaining vertical rhythm you could still do so with a more proportional leading: take a look at [Mark Boulton's approach](http://www.markboulton.co.uk/journal/incremental-leading) (he aligns every 5th sidenote line with a main column line instead of aligning every line).

**Comment by ghost** [comment]
@crmackay Thank you for working on hugo templates. Looking forward to seeing your work!

**Comment by clayh53** [comment]
I'll take a look at making that sidenote leading an option in the scss file. Thanks for that link.

-Clay

**Comment by sotojuan** [comment]
Wow, this is awesome! Going to convert my existing jekyll site to this over the weekend.

**Comment by daveliepmann** [comment]
See https://github.com/edwardtufte/tufte-css/issues/31 for links to other applications.

Since there's nothing actionable on this ticket, I will close it. The information will remain for anyone who looks or asks for Jekyll applications. Thanks.
