### ISSUE TITLE
Fullwidth figure caption misaligned

### ISSUE THREAD

**Issue by godbyk** [edwardtufte/tufte-css#61]
The caption of the fullwidth figure example is misaligned. It doesn't align with the sidenotes  Nor is it centered or flush left across the figure width.

**Comment by daveliepmann** [comment]
You are absolutely correct. I've been meaning to take a deep dive on figcaption positioning in general, since the current solution is a hack. We are tracking this concern in issue #44.

**Comment by daveliepmann** [comment]
I should say, not exactly a hack, but definitely not in alignment with sidenotes in general, which is (as you note) wrong and unacceptable.
