### ISSUE TITLE
ET Bembo -> ET Book

### ISSUE THREAD

**Issue by daveliepmann** [edwardtufte/tufte-css#64]
The font that was ET Bembo has changed to ET Book. All references should reflect this change, including file and folder names, links, and references in the text of `index.html`. Help would be appreciated on this task.

**Comment by daveliepmann** [comment]
See https://github.com/edwardtufte/et-book/commit/7e8f02dadcc23ba42b491b39e5bdf16e7b383031

**Comment by mrzool** [comment]
Hi Dave, any info on the reasons behind the choice?

Pure curiosity.

**Comment by godbyk** [comment]
@mrzool I'm guessing it's to avoid any potential legal complaints about the name "Bembo".

**Comment by daveliepmann** [comment]
I was entirely out of the loop on this change, but I imagine it was to pre-empt any trouble, as @godbyk suggests.

**Comment by vyp** [comment]
I thought it was because of https://github.com/edwardtufte/et-book/issues/4, but looks like the owner didn't respond to that. Anyways, linking because it has a bit more information if anyone's interested.

**Comment by mrzool** [comment]
Makes sense. Thanks.
