### ISSUE TITLE
Automatic sidenote reference tags with JavaScript

### ISSUE THREAD

**Issue by mplewis** [edwardtufte/tufte-css#66]
Hello! Thanks for your work on Tufte CSS, @daveliepmann.

I read in #51 that you do not want to add any JS to this project, which is totally understandable. I am OK with a little bit of JavaScript for my personal website, and I wanted to share something that might make life easier for other users of Tufte CSS.

I wrote [a short script](https://gist.github.com/mplewis/74cc60044057f7fad1a7) that simplifies adding sidenotes. Now you simply have to add the `<span class="sidenote">...</span>` tag, and this script adds the `label` and `input` tags for you.

Hopefully this helps other people with the verbose syntax for sidenotes.

**Comment by daveliepmann** [comment]
:+1:

**Comment by daveliepmann** [comment]
Thanks for your contribution. I'm closing this, but it will stick around as a reference for others in the future who search for sidenote-adding JavaScript. Cheers!
