### ISSUE TITLE
Unnecessary Horizontal Scroll Bars 

### ISSUE THREAD

**Issue by edent** [edwardtufte/tufte-css#67]
On the latest desktop releases of Firefox, Chrome, and Opera - horizontal scroll bars are shown, even when no scrolling is possible.

![overflow](https://cloud.githubusercontent.com/assets/837136/11163300/6500dcc6-8ac1-11e5-9d4a-2986c5d49bbb.png)

This is caused by the use of `overflow-x: scroll;`

I would suggest changing it to `overflow-x: auto;` to ensure that the scroll bars are only displayed when needed.

Ref: https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-x

**Comment by ghusse** [comment]
+1

**Comment by akshayjshah** [comment]
:+1:

**Comment by daveliepmann** [comment]
While I've seen these (ugly, out of place) scrollbars previously, I can't currently reproduce this issue on Chrome, Safari, or Firefox on the two MacBooks I have available. I only see scrollbars when scrolling.

**Comment by edent** [comment]
@daveliepmann as you can see from the screen shot, this behaviour is inconsistent across operating systems. If the change doesn't adversely affect OSX, it would be beneficial for users of Linux & (probably) Windows.

**Comment by edent** [comment]
Android  users are also affected - Marshmallow, latest builds of Chrome, Android Browser, and Opera.

![_20151213_103202](https://cloud.githubusercontent.com/assets/837136/11766787/27d707c4-a18e-11e5-8d36-6f862d4ddaf7.JPG)
![_20151213_103215](https://cloud.githubusercontent.com/assets/837136/11766785/27d5aa78-a18e-11e5-892f-5c34fd070649.JPG)
![_20151213_103150](https://cloud.githubusercontent.com/assets/837136/11766786/27d6cb38-a18e-11e5-9c2d-0cdb14fee012.JPG)

**Comment by bolatovumar** [comment]
Issue is present on the latest versions of Opera, Chrome, Firefox and IE11 on my machine running Win7

![capture](https://cloud.githubusercontent.com/assets/1934678/12004318/ec013262-ab04-11e5-960a-cbdb85fe90e6.PNG)

Pull request [https://github.com/edwardtufte/tufte-css/pull/68](https://github.com/edwardtufte/tufte-css/pull/68) solves the issue

**Comment by daveliepmann** [comment]
Thanks for everyone's diligent contributions via documenting the issue. Getting your screenshots and reports of the issue on specific devices galvanized me to action when it was Fine On My Machine. Apologies for the delay in getting this resolved.

**Comment by bolatovumar** [comment]
@daveliepmann thanks!
