### ISSUE TITLE
Use `figure` and `figcaption` instead of raw `img`

### ISSUE THREAD

**Issue by daveliepmann** [edwardtufte/tufte-css#7]
`figure` and `figcaption` should be used instead of or in addition to the `fullwidth` class. I mean, we already call them that in the example document! 

See http://html5doctor.com/the-figure-figcaption-elements/

Should involve wrapping figures (with captions) in the element and determining whether any classes need to be deprecated.

**Comment by andreabedini** [comment]
It is also possible to do automatic figure numbering http://tympanus.net/codrops/2013/05/02/automatic-figure-numbering-with-css-counters/

**Comment by daveliepmann** [comment]
This may not be possible for margin notes given how we currently meet our design goal of aligning margin notes with their reference, since `<figure>` is not allowed inside `<p>`.

**Comment by daveliepmann** [comment]
`<figure>` has been incorporated for figures in the main body text. They do not appear to be the correct tool for margin figures, so I am closing this issue. If the situation changes then please ping this issue to reopen.
