### ISSUE TITLE
fullwidth code

### ISSUE THREAD

**Issue by meditans** [edwardtufte/tufte-css#80]
Hi, I'd like sometimes to use all the horizontal space, like in the `fullwidth` class for images, when displaying code snippets. Is that possible?

**Comment by Norgat** [comment]
Yes. I modify css for it. Look at this commit in my fork:

https://github.com/Norgat/tufte-css/commit/7d32d2b68f15c8e6002045ec1c3a976ea3587024

Now I can add `fullwidth` class to `pre.code`. And I fix showing scrollbar in all cases in `pre.code`.

**Comment by meditans** [comment]
Hi @Norgat, that's exactly what I ended doing after my question, but then I returned at a lesser code width because I liked that version more. Now I'm thinking having a background gradient (when I'm using the full width), for added smoothness.

Thanks for your solution! :)
