### ISSUE TITLE
Links work in sidenotes but not in marginnotes

### ISSUE THREAD

**Issue by ndw** [edwardtufte/tufte-css#82]
It strikes me as odd that a link in a side note works fine, but the same link in a margin note doesn't work at all.

**Comment by daveliepmann** [comment]
You're going to need to give an example of what you mean, either with code or with a screenshot or both. Does it look wrong, and if so, how? Does the link not function?

**Comment by daveliepmann** [comment]
I cannot reproduce this underspecified issue at all. For example, I copied the anchor from sidenote 1 to the following margin note and it looks fine to me:

`<label for="mn-blue-links" class="margin-toggle">&#8853;</label><input type="checkbox" id="mn-blue-links" class="margin-toggle"/>
<span class="marginnote">
<a href="http://www.edwardtufte.com/tufte/books_be"><em>Beautiful Evidence</em></a>
</span>`

@ndw until a clear example is provided I'm tagging this invalid. If none is provided I'll close.

**Comment by ndw** [comment]
Ok. Thank you for your patience. I dug a little deeper into the context and discovered that a link in a marginal note doesn't work if the note appears before the &lt;article> tag. I suppose that's not unreasonable and it's easily fixed by moving the note. In order to give the superscripts a reasonable place to go, I had to move them inside and I missed the underlying cause.

**Comment by daveliepmann** [comment]
Glad to hear a resolution :) Cheers
