### ISSUE TITLE
Make `gh-pages` branch the main branch and remove `master`

### ISSUE THREAD

**Issue by adamschwartz** [edwardtufte/tufte-css#83]
Hey @daveliepmann, after making https://github.com/edwardtufte/tufte-css/commit/e0f7479c1ac4b6b4e93aefe72ce69fc4a07c8250 just now in `master`, then realizing I needed to merge to `gh-pages` to get it live, made me think of this. But I just wanted to double check with you in case there was a specific reason why you were keeping both branches. Lmk! :smile:

**Comment by daveliepmann** [comment]
Wow, sorry about the misspelling! I thought I had double-checked that. 

I originally kept the branches separate so we could do development, pull requests, and so on without affecting the live site. At this point I'm very open to nixing `master` and just running off `gh-pages`.

**Comment by adamschwartz** [comment]
No worries! :P

Ahh, gotcha. Well I just changed the default branch to `gh-pages` but I didn’t remove `master` just yet. https://github.com/edwardtufte/tufte-css/branches says that `master` is “3 commits ahead and 6 commits behind” `gh-pages` (at the time of this writing) so we should probably do a merge both ways or just manually check that we know we’re not losing anything we care about. So I’ll leave that to you if that’s cool. :)

**Comment by daveliepmann** [comment]
`master` removed. I think this will be a lot cleaner. Thanks for the push, Adam.
