### ISSUE TITLE
Figures in margin and adjacent margins

### ISSUE THREAD

**Issue by chsasank** [edwardtufte/tufte-css#87]
Hi,
I think there should be 
1. Way to caption the images in margin notes.`<figure>` and `<figcaption>` as in [here](http://www.w3schools.com/tags/tag_figcaption.asp) do not work inside margin notes.
2. Some margin/padding for `marginnote` class as consecutive margin notes look bad now. 

Have a look at the following snippet and it's rendering.

``` html
<span class="marginnote">
    <img width='156' height='152' src='/assets/images/traffic/input.png' alt="input to preprocess_img">
    <br>Input image to `preprocess_img` (scaled 4x)
</span>

<span class="marginnote">
    <img src='/assets/images/traffic/output.png' alt="input to preprocess_img">
    Processed image (scaled 4x) 
</span>
```

Rendering:
![screen shot 2016-06-01 at 10 55 22 pm](https://cloud.githubusercontent.com/assets/9305875/15719122/1d8fbe74-284c-11e6-9e54-2a2e9cfbc2a0.png)

Thanks,
Sasank.

Edit: Found out that  `<figcaption>` does not work outside `marginnote` either.

**Comment by crmackay** [comment]
you can place captions above or below margin figures by simply putting text before or after your `<img>` element within any given `<span class="marginnote">` . You can't use `<figure>` or `<figcaption>` elements inside `marginnotes` since they are block level elements. `marginnotes` as they are right now are `<span>` elements embedded within `<p>` elements. There are only a few things that are allowed within `<p>` elements, and anything that is a block is not among them. 

You can see an example of a margin figure with text below it at the tufte-css homepage (https://edwardtufte.github.io/tufte-css/)

Let us know if you cannot get this to work, or if you encounter a problem.

**Comment by chsasank** [comment]
> you can place captions above or below margin figures by simply putting text before or after your <img> element within any given <span class="marginnote"> 

Snippet I've used does exactly that. 

```
<span class="margin note"
    <img src='/assets/images/traffic/output.png' alt="input to preprocess_img">
    Processed image (scaled 4x) 
</span>
```

But the result was ugly as shown in the rendering above.

Thanks for your response,
Sasank.

**Comment by crmackay** [comment]
hmm... so you're image width appears to be less than the margin column width. tufte-css only defines a max-width for `<img>` elements. You could get around this:
Either:
- by creating a `<span class="margin-fig-caption">` element within your marginnote, and playing around with `width` and `display:block` style attributes. 
- or - using a larger image file
- or - there are probably a few more `html` markup strategies you could use to get the stuff inside your `<span class="marginnote">` to look the way you want..

**Comment by chsasank** [comment]
Thanks for your suggestions.
My (noobish?) solution was this:

```
<span class="marginnote">
    <img width='156' height='152' src='/assets/images/traffic/input.png' alt="input to preprocess_img">
    <br>Input image to `preprocess_img` (scaled 4x)
</span>

<span class="marginnote">
    <br><img src='/assets/images/traffic/output.png' alt="input to preprocess_img">
    <br>Processed image (scaled 4x) 
</span>
```

In browser:
![screen shot 2016-06-08 at 2 28 43 am](https://cloud.githubusercontent.com/assets/9305875/15874429/c1907ac6-2d20-11e6-9d23-25defb7f3b3c.png)

I have almost zero experience with CSS and HTML, but I just wanted to point out possible improvements to the tufte CSS through this issue.

Thanks,
Sasank.

**Comment by crmackay** [comment]
Looks better! Thanks for posting this. I agree it is a good observation and identifies a potential place for improvement.

**Comment by daveliepmann** [comment]
Looks like this was resolved with `<br/>` and has some good custom solutions.
