### ISSUE TITLE
Nested lists' percent width causes unusably narrow element width

### ISSUE THREAD

**Issue by kevinmarks** [edwardtufte/tufte-css#91]
if you put a list inside a list, or a blockquote inside a list, they get narrower and narrower to the point of farce

**Comment by daveliepmann** [comment]
Replicated. In the future, please remember that the more detail and rigor you provide reporting an issue, the easier it can be replicated and addressed.

**Comment by daveliepmann** [comment]
Only top-level lists (e.g. within sections) are now width-restricted. This should resolve the issue. If you have other examples of the problem, or if this solution interferes with other scenarios, please provide examples.
