### ISSUE TITLE
Sidenote for epigraphs or blockquotes formatting gone wrong

### ISSUE THREAD

**Issue by statzhero** [edwardtufte/tufte-css#92]
When I include the sidenode `label` within a blockquote, footer or epigraph the styling seems to go wrong, ie the placement is more to the left than a normal sidenote. Can someone confirm that or am I missing something? I have a live example if that would help.

**Comment by crmackay** [comment]
can you provide an example (code, screen grab, live example...or any combination thereof)

**Comment by statzhero** [comment]
First, let me say you're doing great work and I appreciate the hard efforts. 

The example is in sidenote 1: [https://statshero.github.io/generalism-essay](https://statshero.github.io/generalism-essay) 
(please ignore content haha)

**Comment by crmackay** [comment]
So this seems to be a result of the `<blockquote>` elements having a smaller width than `<p>` elements. A CSS selector could be used to selectively bump out sidenotes in blockquotes..I don't have time to do that right now, so someone else is free to jump on this if so inclined.

Edit: and also left align them...

**Comment by statzhero** [comment]
The only thing I can tell is that `114 blockquote footer :not(.sidenote)` does not seem to work. Then again, I don't know how CSS works.

**Comment by crmackay** [comment]
i was thinking something more like

``` css
blockquote .sidenote {
    margin-right: -73%;
    text-align: left;
}
```
