### ISSUE TITLE
clear right and final margin note

### ISSUE THREAD

**Issue by yb66** [edwardtufte/tufte-css#95]
Hi,

I just had cause to add a margin note as the very final part of an article. When rendered, it dropped beneath the article. All other margin/side notes rendered where I'd expect. I tracked it down to the [`clear: right` inside a `.sidenote, marginnote` declaration](https://github.com/edwardtufte/tufte-css/blob/gh-pages/tufte.css#L172).

I tried removing the declaration altogether and noticed no rendering bother created elsewhere, but it did fix this problem. It's been there since the very first commit so I can't find any reason why it was added.

I'm using a modified version of Tufte CSS, so maybe it's just me, but it may affect others.

Regards,
iain

**Comment by daveliepmann** [comment]
Could not replicate. Closing this until we have an example that's verified in an unmodified version of the project.
