### ISSUE TITLE
request: monospaced version of et-book

### ISSUE THREAD

**Issue by gamecubate** [edwardtufte/tufte-css#97]
It would be nice to have a monospaced version of et-book for such use cases as stacked numeric value displays. Here's [an example](http://alexr.ca/pages/dev/mayorhood/) of why this would be desirable (for me at least). The cash-remaining value keeps changing width, which is a bit jarring.

![image](https://cloud.githubusercontent.com/assets/1483884/18172443/6c4cbac4-7033-11e6-92ee-236c475bf9e4.png)

**Comment by daveliepmann** [comment]
I think Tufte CSS would be eager to incorporate a monospace variation of the base font it uses, but to my knowledge such a version of ET Book doesn't exist. You can raise an issue in [that project repo](https://github.com/edwardtufte/et-book), but I don't expect anyone to jump on such a substantial project in the near term.

[When brash, young Tufte CSS handled tables](https://github.com/edwardtufte/tufte-css/tree/94ac0dfc49729269523b9234c853b27f5458d6f2), our solution for situations such as this was Trebuchet. I think that would suit your case well.
