### ISSUE TITLE
Faux Small Caps

### ISSUE THREAD

**Issue by anipaq** [edwardtufte/tufte-css#99]
While Tufte did use small capitals to start a section in his later books, HTML/CSS does not support true small capitals. As Matthew Butterick notes in the [“Small Caps”](http://practicaltypography.com/small-caps.html) chapter of _Practical Typography_: “don’t use the CSS prop­erty `font-vari­ant: small-caps`. Ever. These op­tions do not pro­duce small caps. They pro­duce in­fe­rior counterfeits.” 

I believe the use of these faux small caps in the `newthought` class violates the spirit of Tufte’s typographic style.

**Comment by daveliepmann** [comment]
What do you suggest instead?

**Comment by anipaq** [comment]
Some typefaces, such as EB Garamond and Alegreya, have their true small capitals as separate font files that can be used in a situation like that. Long term I would suggest adding separate small caps font file to the ET Book typeface.

Until that point I would recommend eliminating the `newthought` class altogether because without the small capitals there is not enough indication that a new section has started. There is no justification good enough for using faux small capitals because they disrupt the overall color of the text.

**Comment by daveliepmann** [comment]
A pull request to add a separate small caps font files to ET Book would, I expect, be welcome in [that repo](https://github.com/edwardtufte/et-book). 

If the proposal here is to remove `newthought` functionality without a replacement, I think we'll pass. I empathize with the Butterick position that small-caps is poorly implemented in CSS, but the solution therefore is to not use `newthought`. For the moment I don't find it egregious enough to remove without replacement.

**Comment by adrientetar** [comment]
font-feature-settings: 'smcp';

or

font-variant-caps: small-caps;
